### ISSUE TITLE
Blender 3.2 only rendering first region

### ISSUE THREAD

**Issue by kingsushi001** [p2or/blender-renderborder#6] opened 2022-07-07 19:48 UTC
Hi

I have set up my camera and borders like yours:
![](https://camo.githubusercontent.com/e4d4138b27c571c8706ce827c32237890a77bd192baaba49d5f4261eef0e7fec/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f74436f78702e676966)

But when rendering the frames/borders with ctrl+F12, it only renders the first frame/region for the entire "animation".
Did I miss something?

**Comment by p2or** [comment] 2022-07-07 19:58
Hi @kingsushi001,

as mentioned in the [gotchas section](https://github.com/p2or/blender-renderborder#gotchas), that's caused by a current limitation of Blender. I'd recommend use [Loom](https://github.com/p2or/blender-loom) to render.

Hope this helps though. Closing for now, if something else comes up, just let me know.

Cheers,
Christian

**Closed as completed by p2or** 2022-07-07 19:58 UTC

**Comment by kingsushi001** [comment] 2022-07-07 20:09
Aaaah, so that's what was meant by that. I understood it as I can't animate a whole scene and expect it to work. lol

Thanks for clearing it up.

**Comment by p2or** [comment] 2022-07-07 20:23
No problem @kingsushi001, glad I could help.

Not a native speaker, if you have any idea how we can write this more clearly, please let me know, submit a patch or whatever... I'd appreaciate any help.

Cheers,
Christian
